version: '3.8'
services:
  # bank-rega-db:
  #   image: container-registry.oracle.com/database/free:latest
  #   ports: 1521:1521
  #   environment:
  #     - ORACLE_PWD=1234
  #     - ORACLE_USER=system
  #     - ORACLE_SID=xe
  #   networks:
  #     - bank-rega-network
  bank-rega-java-be:
    image: bank-rega-java:1.0
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@host.docker.internal:1521/xe
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=oracle.jdbc.OracleDriver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_SHOW-SQL=true
    depends_on:
      - bank-rega-fe
    networks:
      - bank-rega-network
  bank-rega-fe:
    image: bank-rega-fe-dev:1.0
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:3000
      - VITE_NASABAH_URL=/nasabah
    networks:
      - bank-rega-network

networks:
  bank-rega-network:
    name: bank-rega-network